language: python

python:
  - "2.6"
  - "2.7"

env:
  global:
    - BEANSTALKD=./beanstalkd

install:
  # Install most recent beanstalkd from source
  - wget https://github.com/kr/beanstalkd/archive/v1.9.tar.gz
  - tar xf v1.9.tar.gz
  - make -C beanstalkd-1.9/
  - mv beanstalkd-1.9/beanstalkd .
  - beanstalkd -v
  - python bootstrap.py
  - bin/buildout

script: bin/specs

notifications:
  email:
    - phillip.oldham@gmail.com
